<?php

return [
    'email' => [
        'title' => 'Ändere deine Mail-Adresse',
        'updated' => 'Deine Mail-Adresse wurde geändert.',
    ],
    'password' => [
        'title' => 'Ändere dein Passwort',
        'requirements' => 'Dein Passwort sollte mindestens acht Zeichen lang sein.',
        'updated' => 'Dein Passwort wurde geändert.',
    ],
    'two_factor' => [
        'button' => 'Konfiguriere 2-FA Authentifizierung',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'The token provided was invalid.',
        'setup' => [
            'title' => 'Setup two-factor authentication',
            'help' => 'Can\'t scan the code? Enter the code below into your application:',
            'field' => 'Enter token',
        ],
        'disable' => [
            'title' => 'Disable two-factor authentication',
            'field' => 'Enter token',
        ],
    ],
];
